Feature/pto events: CRUD for PTO and Events
tech-university-india/developer-dashboard-backend pull request #11
Opened 2023-02-12 13:57 UTC by sanyam9

2023-02-12 14:44 UTC, sidx255 approved these changes

2023-02-13 09:58 UTC, ashutoshmck commented on src/routes/dashRouter.js
> +
I suggest that we should have different routers for different modules, it helps in segregation of routes.

2023-02-13 10:01 UTC, ashutoshmck commented on tests/services/event.test.js
> +      jest.spyOn(db.project_events, 'destroy').mockRejectedValue(new Error('Error'));
I suggest that you should put a more appropriate error message , which specifies what kind of error it is

2023-02-13 10:02 UTC, ashutoshmck requested changes
Please resolve all the concerns since they can be seen at multiple places

2023-02-15 05:07 UTC, SNEHA1009TRIVEDI approved these changes

2023-02-15 05:26 UTC, ashutoshmck approved these changes

2023-02-15 05:27 UTC, merged